### ISSUE TITLE
Hadoop, run java wordcount program

### ISSUE THREAD

**Issue by vluu2** [csula/cs-tools#1]
After running on node1:
- hadoop namenode -format
- start-all.sh
Next step: 
hadoop dfs -copyFromLocal gutenberg/ /user/vagrant/gutenberg 

gutenberg not detected locally so I cannot move to next step (previously worked for old instructions)

**Comment by john-csula** [comment]
`node1` .. `node4` are meant for the cluster mode.

Let me update the instructions accordingly.
